### ISSUE TITLE
minibroker shouldn't auto-register

### ISSUE THREAD

**Issue by duglin** [osbkit/minibroker#14]
I believe that minibroker assumes it's being installed into the same kube cluster that will be used by the applications of those services. I don't believe this is a safe assumption - especially when one of the main uses for svc-cat is to leverage 3rd party (external) services. Nor do I think we can assume that the scope of the broker (cluster vs namespace-scope) can be defaulted.

The helm chart for minibroker should do ONLY what people asked, which is to install minibroker in this cluster. If they then want it to be registered as a broker with this cluster's svc-cat then they can ask for it.

I found this because I was playing with this chart and could not figure out why I was seeing a broker even though I never asked for one to be installed.

I think it might be ok to add a flag to auto-register, but I don't think it should be the default. Unless the intent is for this to be ONLY for demo purpose - where there's only ever one kube cluster involved.

**Comment by carolynvs** [comment]
The way minibroker works (and helm 2 works) there is no way to install minibroker on anything _other_ than the cluster where resources will be provisioned.

Maybe with helm 3 that could be considered, but that's a few months away.

**Comment by carolynvs** [comment]
I'm going to close for now since there isn't anything actionable that we can do at this time. Once we know more about Helm 3 when it's released, we can revisit.
