### ISSUE TITLE
postgres provisioning failing

### ISSUE THREAD

**Issue by jpreese** [osbkit/minibroker#26]
When attempting to provision a postgres database (plan 11-0-0), the Kubernetes cluster is reporting the following error on container creation.

```
Error executing 'postInstallation': 2019-04-22 15:39:31.391 UTC [90] FATAL:  data directory "/opt/bitnami/postgresql/data" has wrong ownership
2019-04-22 15:39:31.391 UTC [90] HINT:  The server must be started by the user that owns the data directory.
```

**Comment by carolynvs** [comment]
This looks to be a problem with the postgres chart, and not minibroker. We just call out to the upstream stable helm charts, so I think you'd want to ask for help with: 

https://github.com/helm/charts/tree/master/stable/postgresql
